### PR TITLE
PclZip library added to remove ZipArchive dependency

### PR DESCRIPTION
**Pull request by dcooperdalrymple**
The environment I was working with to use this plugin server did not have ZipArchive enabled nor would I have been able to get a system administrator to do so. The addition of PclZip as an optional library gets rid of this dependency (though it is still supported; similar to how WordPress handles zip archives). This does add a small amount of bloat, but it is negligible.

### CODE REVIEW

**Comment by YahnisElsts** [comment]
I'm not sure about this.

- Is PclZip still maintained? [The most recent release](http://www.phpconcept.net/pclzip/release-notes) was in 2009. On the other hand, one would assume that WP core developers have already fixed any major issues.
- Code duplication. If you're going to have multiple ZIP readers, there really needs to be a unified interface of some kind.
- Mixed whitespace. It looks the added code uses spaces for indentation while the rest of the file uses tabs. This is a pretty minor issue, but preserving consistency is useful. Please use tabs for indentation.
- Finally, about a third of the changes is just adding/removing whitespace.

**Comment by dcooperdalrymple** [comment]
Here are my alterations and notes:

- The version of PclZip that I'm using here is directly from the WordPress repository. From my experience,  despite its age it is still one of the better open source libraries for zip archive purely in php. Even so, it will only act as a backup to ZipArchive.
- The new commit creates the class Wpup_Archive (this can be renamed if you would like to keep it separate from the other Wpup_ classes) which acts as a wrapper to unify the two libraries.
- The only major discrepancy between ZipArchive and PclZip in the scope of this class is how they handle file information. I decided to go down PclZip's route by returning a full list of the zipped file information rather than getting that information by index. This could be implemented the other way around if that is preferred.
- I'm relatively new to using Git and not certain exactly how to undo those whitespace issues. I did my best to convert everything back to tabs where possible.

**Comment by YahnisElsts** [comment]
It's a step in the right direction, but I think that all of those conditionals inside `Wpup_Archive` should be replaced with polymorphism (i.e. instead of one class, there should be two: one that uses ZipArchive and one that uses PclZip, and probably a static factory method that picks the appropriate class based on what's available).

Also, the part of the code that uses ZipArchive doesn't work. It throws a notice:
`Notice: Undefined variable: zip in [...]/extension-meta.php on line 528`

... and then it returns error 500: 
`Package "example" exists, but it is not a valid plugin or theme`.

There's another bug on line 544 where it modifies the file `$info` array instead of adding it to $list. Even if that is fixed, the archive parser throws a new error:
`Warning: Illegal string offset 'content' in [...]/extension-meta.php on line 90`

Unfortunately, I don't have any more time today, but I'll look into this tomorrow.

**Comment by YahnisElsts** [comment]
All right, take a look at this version:
https://gist.github.com/YahnisElsts/dccaa3a4d35c0910114ece4f89c924c1

**Comment by dcooperdalrymple** [comment]
The PclZip implementation works for me, and the abstract class is much cleaner. Sorry about the ZipArchive errors; I didn't have the environment to test it properly nor the time. Nice work!

**Comment by YahnisElsts** [comment]
Thank you. I'll run some more tests later, and if all goes well I'll merge it.

**Pull request merged**
